Reverse the date order of the bookmark list so most recent are at the top.
AndBible/and-bible pull request #1580
Opened 2021-08-14 05:27 UTC by agrogers

My list is now realllly long. It takes 5 seconds or more to scroll to the bottom of the bookmarks. But almost always I am looking for bookmarks I just created or created recently... which were at the bottom. Now they are at the top.

I didn't know how to add an extra sort option - Biblical Order, Date Order, Date Order Desc.

There is no string i could use for the latter anyhow. So i have just reversed the current one.

2021-08-22 08:30 UTC, agrogers commented
I timed how long it takes me to scroll to the bottom of my list today. 13 seconds! Would be great to add this or include an additional option on the sort button that does it.

2021-08-23 06:42 UTC, tuomas2 commented
Is this ready to review?

2021-08-23 07:03 UTC, agrogers commented
Do you mean is it complete? If so, yes. I have only been adding pull requests that i think are ready.

2021-08-23 07:33 UTC, tuomas2 commented
Okay, marking it 'ready for review' then :-)

2021-08-23 07:44 UTC, tuomas2 commented on db/src/main/java/net/bible/android/database/bookmarks/BookmarksDao.kt
> +CASE WHEN :orderBy = 'CREATED_AT_DESC' THEN Bookmark.createdAt END DESC,
I believe this should be

```suggestion
CASE WHEN :orderBy = 'CREATED_AT_DESC' THEN Bookmark.createdAt DESC END,
```

2021-08-23 07:48 UTC, tuomas2 commented on db/src/main/java/net/bible/android/database/bookmarks/BookmarksDao.kt
> +    WHEN :orderBy = 'CREATED_AT_DESC' THEN Bookmark.createdAt
And here I would feel that you meant

```suggestion
    WHEN :orderBy = 'CREATED_AT_DESC' THEN Bookmark.createdAt DESC
```

Or what do you think?

2021-08-23 07:50 UTC, tuomas2 commented on app/src/main/java/net/bible/android/view/activity/bookmark/Bookmarks.kt
> +            else -> BookmarkSortOrder.CREATED_AT_DESC
Shouldn't this be full loop between BIBLE_ORDER -> CREATED_AT_DESC -> CREATED_AT -> BIBLE_ORDER? Now we don't go ever to CRATED_AT.

2021-08-23 07:52 UTC, tuomas2 commented on app/src/main/java/net/bible/android/view/activity/bookmark/Bookmarks.kt
> +            else -> BookmarkSortOrder.CREATED_AT_DESC
```suggestion
            BookmarkSortOrder.BIBLE_ORDER -> BookmarkSortOrder.CREATED_AT_DESC
            BookmarkSortOrder.CREATED_AT_DESC -> BookmarkSortOrder.CREATED_AT            
            BookmarkSortOrder.CREATED_AT -> BookmarkSortOrder.BIBLE_ORDER
            else -> BookmarkSortOrder.CREATED_AT_DESC
```

2021-08-23 07:53 UTC, tuomas2 requested changes
Check my suggestions and apply them if you think they are correct. Please also test quickly if they work as intended.

2021-08-23 08:24 UTC, agrogers commented
Um, i know my original pull request works - i have been using it on.

And I remember getting confused by where the END of the case should be
placed - i reckon i have it right.

However you are correct in that my pull request never sorts by Created_At
in an ascending order. I mentioned that in the original comment I think. I
didn't know how to add that as an extra option in the button press loop.
But it seems like you have done it and it was much easier than i realised.

___________________________
*www.TenOutOfTen.org* <https://www.TenOutOfTen.org>
***@***.***
(+61) 0477 174 193 (Australia)
(+95) 09 250018669 (Myanmar)



On Mon, 23 Aug 2021 at 17:53, Tuomas Airaksinen ***@***.***>
wrote:

> ***@***.**** requested changes on this pull request.
>
> Check my suggestions and apply them if you think they are correct. Please
> also test quickly if they work as intended.
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/AndBible/and-bible/pull/1580#pullrequestreview-735819661>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/ADKGTJVUX3YRBVMZXNQW2GTT6H47JANCNFSM5CEXMINA>
> .
>

2021-08-23 08:36 UTC, tuomas2 commented
@agrogers here's the syntax: https://sqlite.org/lang_expr.html . It can indeed work either way but have side-effect if placed wrongly.

2021-08-23 10:18 UTC, agrogers commented
Thanks for the link. Happy to look at this again but cant do it until the
weekend.

___________________________
*www.TenOutOfTen.org* <https://www.TenOutOfTen.org>
***@***.***
(+61) 0477 174 193 (Australia)
(+95) 09 250018669 (Myanmar)



On Mon, 23 Aug 2021 at 18:36, Tuomas Airaksinen ***@***.***>
wrote:

> @agrogers <https://github.com/agrogers> here's the syntax:
> https://sqlite.org/lang_expr.html . It can indeed work either way but
> have side-effect if placed wrongly.
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/AndBible/and-bible/pull/1580#issuecomment-903559364>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/ADKGTJX5EW2LFPBHVL4KWWLT6ICAVANCNFSM5CEXMINA>
> .
>

2021-08-23 10:22 UTC, tuomas2 commented
Okay I made changes and will merge and check if it works...

2021-08-23 10:22 UTC, merged

2021-08-23 10:30 UTC, agrogers commented
Sweet. Thank you

___________________________
*www.TenOutOfTen.org* <https://www.TenOutOfTen.org>
***@***.***
(+61) 0477 174 193 (Australia)
(+95) 09 250018669 (Myanmar)



On Mon, 23 Aug 2021 at 20:22, Tuomas Airaksinen ***@***.***>
wrote:

> Merged #1580 <https://github.com/AndBible/and-bible/pull/1580> into
> develop.
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/AndBible/and-bible/pull/1580#event-5193513350>, or
> unsubscribe
> <https://github.com/notifications/unsubscribe-auth/ADKGTJUBS4G4JEDU5DAMDBDT6IOO7ANCNFSM5CEXMINA>
> .
>